### ISSUE TITLE
Issue when test collection

### ISSUE THREAD

**Issue by ElMohMoh** [ozanturksever/mock_cloud_firestore#1]
Hello I want to make a unit test for testing a collection (folwing test "check all projects") without using widget but my test failed. How can I fix this?

Here is the code made by the example.dart:

`import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:mock_cloud_firestore/mock_cloud_firestore.dart';

import 'test_data.dart';

typedef CollectionReference CollectionGet(String path);

class BackendApi {
  CollectionGet collectionGet;

  BackendApi(this.collectionGet);

  Future<Map<String, dynamic>> project() async {
    DocumentReference docRef = collectionGet("projects").document("1");
    DocumentSnapshot docSnap = await docRef.get();
    return docSnap.data;
  }

  Future<QuerySnapshot> projects() async =>
      collectionGet("projects").getDocuments();
}

class FirebaseDepWidget extends StatelessWidget {
  BackendApi backend;

  FirebaseDepWidget(this.backend);

  @override
  Widget build(BuildContext context) {
    return FutureBuilder(
      future: backend.project(),
      builder: (BuildContext context, AsyncSnapshot snapshot) {
        if (!snapshot.hasData) {
          return Text("Loading...");
        }
        return Text("${snapshot.data["title"]}");
      },
    );
  }
}

MockCloudFirestore getMockCloudFirestore() {
  return MockCloudFirestore(getTestData());
}

void main() {
  MockCloudFirestore mcf = getMockCloudFirestore();

  //BackendApi realBackend = BackendApi(Firestore.instance.collection);
  BackendApi mockBackend = BackendApi(mcf.collection);

  testWidgets('check task info ', (WidgetTester tester) async {
    await tester.pumpWidget(
      MaterialApp(
        home: Container(
          child: FirebaseDepWidget(mockBackend),
        ),
      ),
    );
    await tester.pump(Duration
        .zero); // Duration.zero is required or you get a timer exception
    expect(find.text("test project 1"), findsOneWidget);
  });

  test('check all projects', () async {
    QuerySnapshot qs = await mockBackend.projects();
    expect(qs.documents.length, 2);
  });
}
`
Here is the issue:

`D:\Documents\dev\hangar\mock_cloud_firestore (master)
λ flutter test example\example.dart
00:12 +1 -1: check all projects [E]
  NoSuchMethodError: The getter 'documents' was called on null.
  Receiver: null
  Tried calling: documents
  dart:core                   Object.noSuchMethod
  example\example.dart 69:15  main.<fn>
  ===== asynchronous gap ===========================
  dart:async                  _AsyncAwaitCompleter.completeError
  example\example.dart        main.<fn>
  ===== asynchronous gap ===========================
  dart:async                  _asyncThenWrapperHelper
  example\example.dart        main.<fn>

00:12 +1 -1: Some tests failed.`

**Comment by ozanturksever** [comment]
`getDocuments` wasn't implemented,  `0.0.5` has it. Also added your example as test, you can check that out.
