### ISSUE TITLE
How to support Timestamp fields?

### ISSUE THREAD

**Issue by sceee** [ozanturksever/mock_cloud_firestore#7]
How can timestamp fields be used in the test data?
It seems that dart:covert cannot deserialize the JSON to Firestore Timestamp values because in Json, it's either just a string or an int.

Is there any possibility to support Timestamp values with the current state of this library?

**Comment by ozanturksever** [comment]
can you add a test for it? then i can try to implement it. You can find tests in `test/` directory

**Comment by DanMossa** [comment]
I'm also interested in supporting timestamp fields.

When I export my stuff from cloud firestore this is what I get for timestamps

`{"_seconds": 1555641180, "_nanoseconds": 0},`

**Comment by anthony-bernardo** [comment]
Any news on that ?

**Comment by ozanturksever** [comment]
i believe #18 resolved this issue, published 0.0.20 with it.

thanks @mentoc3000
