### ISSUE TITLE
Missing Implementation for DocumentReference Snapshots

### ISSUE THREAD

**Issue by sceee** [ozanturksever/mock_cloud_firestore#8]
According to what I see in the code, the implementation for DocumentReference Snapshots is missing so that calls to it return null.

**Example:**
```
Stream<DocumentSnapshot> myDocumentStream = myFirestoreMock.myCollection
          .document('123123123')
          .snapshots();
```
returns null even though there are documents in the sample database that can be retrieved with `.get()`.

Is there any specific reason snapshots() is not supported for documents (because it seems like there is an actual `when -> answer` for MockCollectionReference)?

**Comment by ozanturksever** [comment]
added docref.snapshots() impl with 0.0.10, please check it out.

**Comment by sceee** [comment]
@ozanturksever thanks for the fast implementation, works great so far!
